import { HOSTS, HOST_ANSWER_LINES } from "../data/seedData";
import type { SessionInfo } from "./types";

/** Premium tool: "AI transcription" — in the prototype it composes a
 *  plausible notes file from the recording's chapters and downloads it. */
export function downloadTranscript(sesh: SessionInfo) {
  const host = HOSTS.find((h) => h.id === sesh.hostId);
  const hostName = sesh.hostId === "you" ? "You (host)" : host?.name ?? "Host";
  const lines: string[] = [
    `PREP.IO — SESSION TRANSCRIPT (AI-generated, prototype)`,
    ``,
    `Session: ${sesh.title}`,
    `Host: ${hostName}${host ? ` — ${host.headline}` : ""}`,
    `Recorded: ${sesh.vod?.recordedOn ?? ""} · ${sesh.vod?.durationLabel ?? ""}`,
    ``,
    `----------------------------------------`,
  ];
  (sesh.vod?.chapters ?? []).forEach((ch, i) => {
    const script = HOST_ANSWER_LINES[i % HOST_ANSWER_LINES.length];
    lines.push(
      ``,
      `[${ch.t}] Q${i + 1} — ${ch.askedBy}:`,
      `  "${ch.question}"`,
      ``,
      ...script.map((l) => `  ${hostName}: ${l}`),
    );
  });
  lines.push(
    ``,
    `----------------------------------------`,
    `Generated by Prep.io Premium transcription (mocked).`,
  );
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `prepio-transcript-${sesh.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
